import { Link } from "wouter";
import SiteFooter from "@/components/SiteFooter";

const EFFECTIVE = "June 5, 2026";
const CONTACT = "legal@estimatorx.pro";
const DOMAIN = "https://estimatorx.pro";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-10">
      <h2 className="text-xl font-black font-serif uppercase mb-4 text-[#1A1A1A] border-l-4 border-[#E85D26] pl-4">{title}</h2>
      <div className="text-[#3A3530] leading-relaxed space-y-4">{children}</div>
    </div>
  );
}

export default function TermsOfUse() {
  return (
    <div className="min-h-[100dvh] bg-[#F7F4F0] text-[#1A1A1A]">

      {/* Header */}
      <header className="sticky top-0 z-50 w-full border-b border-[#E0DAD3] bg-white shadow-sm">
        <div className="container mx-auto px-4 h-20 flex items-center justify-between">
          <Link href="/">
            <img src="/logo.svg" alt="EstimatorX.pro Logo" className="h-16 object-contain" />
          </Link>
          <Link href="/" className="text-sm font-bold uppercase tracking-wider text-[#444] hover:text-[#E85D26] transition-colors">
            ← Back to Home
          </Link>
        </div>
      </header>

      <main className="container mx-auto px-4 py-16 max-w-3xl">

        {/* Title block */}
        <div className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-[2px] bg-[#E85D26]" />
            <span className="text-[#E85D26] font-bold uppercase tracking-widest text-sm">Legal</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-black font-serif uppercase mb-4">Terms of Use</h1>
          <p className="text-[#888] text-sm">Effective Date: {EFFECTIVE} &nbsp;·&nbsp; <a href={DOMAIN} className="text-[#E85D26] hover:underline">{DOMAIN}</a></p>
        </div>

        <div className="bg-white border border-[#E0DAD3] p-8 md:p-12">

          <p className="text-[#3A3530] leading-relaxed mb-10">
            These Terms of Use ("Terms") govern your access to and use of EstimatorX.pro ("Service," "we," "us," or "our"). By creating an account or using the Service, you agree to be bound by these Terms. If you do not agree, do not use the Service.
          </p>

          <Section title="1. Use of the Service">
            <p>EstimatorX.pro provides a construction cost estimating tool for personal and professional use. You may use the Service to generate material and labor estimates for construction projects.</p>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Use the Service for any unlawful purpose or in violation of any applicable regulations</li>
              <li>Attempt to reverse-engineer, scrape, or copy the underlying formulas, data, or software</li>
              <li>Share your account credentials with others</li>
              <li>Use automated scripts or bots to access the Service</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
            </ul>
          </Section>

          <Section title="2. Accounts">
            <p>To access most features, you must create an account using your email address. You are responsible for keeping your account secure and for all activity that occurs under your account.</p>
            <p>We reserve the right to suspend or terminate accounts that violate these Terms or are used for fraudulent activity.</p>
          </Section>

          <Section title="3. Payments and Subscriptions">
            <p><strong>One-time print credits.</strong> A $0.99 fee is charged each time a free-tier user generates a print or PDF export of an estimate. This is a non-refundable one-time charge processed via Stripe.</p>
            <p><strong>X Plan subscription.</strong> The X Plan is a monthly subscription at $9.99/month that includes unlimited project saves, PDF plan import, shareable estimate links, and watermark-free print output. Subscriptions are billed monthly and renew automatically until cancelled.</p>
            <p><strong>Cancellation.</strong> You may cancel your X Plan subscription at any time from your account settings. Cancellation takes effect at the end of the current billing period — you will retain access through the period you've paid for.</p>
            <p><strong>Refunds.</strong> All payments are generally non-refundable. If you believe you were charged in error, please contact us at <a href={`mailto:${CONTACT}`} className="text-[#E85D26] hover:underline">{CONTACT}</a> within 14 days of the charge and we will review your request.</p>
          </Section>

          <Section title="4. Estimates Are for Reference Only">
            <p>The estimates generated by EstimatorX.pro are based on national average labor rates (RSMeans data) and field-derived material formulas. They are intended as a starting point and rough guide — <strong>not as final bids, binding contracts, or professional engineering opinions.</strong></p>
            <p>Actual construction costs vary significantly based on local market conditions, site conditions, subcontractor pricing, material availability, and other factors outside our control. We strongly recommend verifying estimates with licensed contractors and suppliers before making financial decisions.</p>
            <p>EstimatorX.pro is not a licensed contractor, engineer, or architect. Nothing produced by the Service constitutes professional construction advice.</p>
          </Section>

          <Section title="5. Intellectual Property">
            <p>All content, formulas, code, design, and branding on EstimatorX.pro are owned by us or our licensors and are protected by applicable intellectual property laws. You may not copy, reproduce, or distribute any part of the Service without our prior written permission.</p>
            <p>Estimate data and content you create using the Service remains yours. By using the Service, you grant us a limited license to store and display your estimates for the purpose of operating the Service.</p>
          </Section>

          <Section title="6. Disclaimer of Warranties">
            <p>The Service is provided "as is" and "as available" without warranties of any kind, express or implied, including but not limited to merchantability, fitness for a particular purpose, or non-infringement.</p>
            <p>We do not warrant that the Service will be uninterrupted, error-free, or that estimates will be accurate for your specific project or location.</p>
          </Section>

          <Section title="7. Limitation of Liability">
            <p>To the fullest extent permitted by law, EstimatorX.pro and its owners, operators, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to financial losses resulting from reliance on estimates produced by the Service.</p>
            <p>Our total liability to you for any claim arising from these Terms or your use of the Service shall not exceed the amount you paid to us in the 12 months preceding the claim.</p>
          </Section>

          <Section title="8. Privacy">
            <p>Your use of the Service is also governed by our <Link href="/privacy/" className="text-[#E85D26] hover:underline">Privacy Policy</Link>, which is incorporated into these Terms by reference.</p>
          </Section>

          <Section title="9. Changes to These Terms">
            <p>We may update these Terms from time to time. When we make material changes, we will update the effective date at the top of this page. Continued use of the Service after changes are posted constitutes your acceptance of the revised Terms.</p>
          </Section>

          <Section title="10. Governing Law">
            <p>These Terms are governed by the laws of the United States. Any disputes shall be resolved in accordance with applicable federal and state law.</p>
          </Section>

          <Section title="11. Contact">
            <p>Questions about these Terms? Contact us at:</p>
            <div className="bg-[#FAF8F5] border border-[#E0DAD3] p-4 mt-2">
              <p className="font-bold">EstimatorX.pro</p>
              <p><a href={`mailto:${CONTACT}`} className="text-[#E85D26] hover:underline">{CONTACT}</a></p>
              <p><a href={DOMAIN} className="text-[#E85D26] hover:underline">{DOMAIN}</a></p>
            </div>
          </Section>

        </div>

        <div className="mt-8 flex gap-6 text-sm text-[#888]">
          <Link href="/privacy/" className="hover:text-[#E85D26] transition-colors">Privacy Policy</Link>
          <Link href="/" className="hover:text-[#E85D26] transition-colors">Back to Home</Link>
        </div>

      </main>

      <SiteFooter />

    </div>
  );
}
