// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/logos/OptionA.tsx": () => import("../components/mockups/logos/OptionA.tsx"),
  "./components/mockups/logos/OptionB.tsx": () => import("../components/mockups/logos/OptionB.tsx"),
  "./components/mockups/logos/OptionC.tsx": () => import("../components/mockups/logos/OptionC.tsx"),
  "./components/mockups/logos/OptionD.tsx": () => import("../components/mockups/logos/OptionD.tsx")
};
